version: "2.1"
services:
  db:
    image: mysql:5.6
    container_name: enterprise_access.db
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - devstack_default
    volumes:
      - enterprise_access_mysql:/var/lib/mysql

  memcache:
    image: memcached:1.4.24
    container_name: enterprise_access.memcache

  app:
    # Uncomment this line to use the official enterprise_access base image
    image: openedx/enterprise_access

    container_name: enterprise_access.app
    volumes:
      - .:/edx/app/enterprise_access/
    command: bash -c 'while true; do python /edx/app/enterprise_access/manage.py runserver 0.0.0.0:18270; sleep 2; done'
    environment:
      DJANGO_SETTINGS_MODULE: enterprise_access.settings.devstack
    ports:
      - "18270:18270" # TODO: change this to your port
    networks:
      - devstack_default
    stdin_open: true
    tty: true

networks:
  devstack_default:
    external: true

volumes:
  enterprise_access_mysql:
